name: Main Branch CI

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      test-script:
        type: choice
        description: 'Select the test script to run' # Updated description slightly
        required: true
        default: 'test:regression' # Default value must be one of the options
        options: # Added options list
          - test:regression
          - test:login
          - test:purchase

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.7.0
          cache: 'npm' # Enable caching for npm

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm install

      - name: Check versions
        run: |
          google-chrome --version
          npx chromedriver --version

      - name: Run tests
        env:
          TEST_SCRIPT: ${{ github.event.inputs.test-script || 'test:regression' }}
        run: xvfb-run --auto-servernum npm run ${{ env.TEST_SCRIPT  }}

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build allure report and history
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Generate compressed allure report
        if: always()
        continue-on-error: true
        run: |
          sudo apt-get install -y zip
          zip -r allure-report.zip allure-report/

      - name: Upload artifact for 10 days
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: allure-report.zip
          retention-days: 10

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
